version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: R00tPSPassw0rd!
      POSTGRES_DB: invoicing_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./ops/pg-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d invoicing_db || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30

  api:
    build:
      context: .
      dockerfile: Invoicing.Api/Dockerfile
    container_name: invoicing-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=invoicing_db;Username=postgres;Password=R00tPSPassw0rd!"
    ports:
      - "8080:8080"

volumes:
  pg_data: {}